name: docker-build-and-publish

on:
  push:
    branches: 
      - main
  pull_request:
    branches: 
      - main

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Docker image
        run: docker build -t ghcr.io/jackbrown1993/growatt-rs485-mqtt .

      - name: Publish Docker image (only on push to main)
        if: github.ref == 'refs/heads/main'
        run: docker push ghcr.io/jackbrown1993/growatt-rs485-mqtt:latest
